# Generated by Django 5.1 on 2024-08-26 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='students',
        ),
        migrations.AddField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='system.student'),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='files',
            field=models.FileField(upload_to='assignments/'),
        ),
    ]
